name = "paapi-server"
main = "src/worker.ts"

compatibility_date = "2026-01-04"

[dev]
port = 1616

[[durable_objects.bindings]]
name = "DO_PAAPI"
class_name = "PaapiDO"

[[migrations]]
tag = "v1"
new_classes = ["PaapiDO"]
